# Generated by Django 5.0 on 2023-12-21 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gpuser',
            name='decryption',
            field=models.TextField(default=''),
        ),
    ]
