# Generated by Django 5.0 on 2023-12-21 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_gpuser_decryption'),
    ]

    operations = [
        migrations.AddField(
            model_name='gpuser',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='gamecovers/'),
        ),
    ]
