# Generated by Django 5.0 on 2023-12-21 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_gpuser_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gpuser',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profilepictures/'),
        ),
    ]
