# Generated by Django 5.0 on 2023-12-21 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_gpuser_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gpuser',
            name='decryption',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
