# Generated by Django 5.0 on 2023-12-20 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamelist',
            name='slug',
            field=models.SlugField(default=''),
        ),
    ]
