# Generated by Django 5.0 on 2023-12-17 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_game_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='g_image',
            new_name='cover_image',
        ),
        migrations.RenameField(
            model_name='gamelist',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='game_id',
            new_name='game',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='user_id',
            new_name='user',
        ),
    ]
