# Generated by Django 5.0 on 2023-12-17 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_rename_g_image_game_cover_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='cover_image',
            field=models.ImageField(blank=True, upload_to='main_app/files/game covers'),
        ),
    ]
