# Generated by Django 5.0 on 2023-12-19 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0013_alter_game_cover_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='cover_image',
            field=models.ImageField(blank=True, default='gamecovers/No_Cover_Image.png', upload_to='gamecovers/'),
        ),
    ]
